### ISSUE TITLE
might be useful if wws actually worked

### ISSUE THREAD

**Issue by breck7** [breck7/wws#9]
what kind of shoddy work is this!!! get this shit working.

**Comment by breck7** [comment]
```
 wws fetch scroll
Updating scroll
Unable to read clocLangs.txt
Unable to read clocLangs.txt
Unable to read clocLangs.txt
Unable to read clocLangs.txt
Updating subfolder 'wws'
Updating subfolder 'sdk'
Updating subfolder 'faq'
Updating subfolder 'sets'
breck@Brecks-MacBook-Pro wws % 
```

**Comment by breck7** [comment]
```
breck@Brecks-MacBook-Pro wws % wws fetch pldb
Updating pldb
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: cd /Users/breck/.wws/pldb && git pull origin
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at Object.execSync (node:child_process:963:15)
    at WWSCli.fetchFolder (/Users/breck/wws/wws.js:213:21)
    at /Users/breck/wws/wws.js:246:49
    at Array.forEach (<anonymous>)
    at WWSCli.fetchCommand (/Users/breck/wws/wws.js:246:22)
    at WWSCli.executeUsersInstructionsFromShell (/Users/breck/wws/wws.js:236:116)
    at Object.<anonymous> (/Users/breck/wws/wws.js:296:44) {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(95) [Uint8Array] [
      101, 114, 114, 111, 114,  58,  32,  99,  97, 110, 110, 111,
      116,  32, 112, 117, 108, 108,  32, 119, 105, 116, 104,  32,
      114, 101,  98,  97, 115, 101,  58,  32,  89, 111, 117,  32,
      104,  97, 118, 101,  32, 117, 110, 115, 116,  97, 103, 101,
      100,  32,  99, 104,  97, 110, 103, 101, 115,  46,  10, 101,
      114, 114, 111, 114,  58,  32, 112, 108, 101,  97, 115, 101,
       32,  99, 111, 109, 109, 105, 116,  32, 111, 114,  32, 115,
      116,  97, 115, 104,  32, 116, 104, 101, 109,  46,  10
    ]
  ],
  pid: 15399,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(95) [Uint8Array] [
    101, 114, 114, 111, 114,  58,  32,  99,  97, 110, 110, 111,
    116,  32, 112, 117, 108, 108,  32, 119, 105, 116, 104,  32,
    114, 101,  98,  97, 115, 101,  58,  32,  89, 111, 117,  32,
    104,  97, 118, 101,  32, 117, 110, 115, 116,  97, 103, 101,
    100,  32,  99, 104,  97, 110, 103, 101, 115,  46,  10, 101,
    114, 114, 111, 114,  58,  32, 112, 108, 101,  97, 115, 101,
     32,  99, 111, 109, 109, 105, 116,  32, 111, 114,  32, 115,
    116,  97, 115, 104,  32, 116, 104, 101, 109,  46,  10
  ]
}

Node.js v20.17.0
breck@Brecks-MacBook-Pro wws % 
```
